version: '3.9'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - db
    ports:
      - "8008:8000"

  db:
    image: postgres:15
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./src/db_schemas:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
